# Generated by Django 4.2.3 on 2023-07-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persons',
        ),
    ]
