# Generated by Django 4.2.3 on 2023-07-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_person_persons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persons',
            new_name='Person',
        ),
    ]
