# Generated by Django 4.2.3 on 2023-07-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_persons_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Blanks',
        ),
    ]
