# Generated by Django 4.2.3 on 2023-07-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='blanks',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='blanks',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
