# Generated by Django 4.2.3 on 2023-07-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_blanks_email_blanks_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
